version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    image: my-python-application-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    image: my-python-application-frontend
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "5000:5000"
